language: node_js

node_js: 8

cache: yarn

branches:
  only:
    - master

install:
  - yarn
  - cd functions && yarn && cd ..

before_script:
  - npm install
  - npm install firebase-tools

script:
  - yarn lint
  - yarn build:prod

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token={$FIREBASE_TOKEN} --non-interactive

